apiVersion: v1
kind: Service
metadata:
  name: devops-stack-service
spec:
  selector:
    app.kubernetes.io/name: DevopsStack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
